language: python
python:
  - "3.6"
node_js: "node"
install:
  - pip install -U pip setuptools
  - pip install python-coveralls nodeenv coverage
  - nodeenv -p
  - npm install
script:
  - coverage run --source=. --omit='.eggs/*' setup.py test
  - coveralls
