language: python
python:
  - "2.7"
  - "3.6"
node_js: "node"
install:
  - pip install -U pip setuptools
  - pip install -U -r requirements.txt
  - pip install python-coveralls
  - pip install nodeenv
  - nodeenv -p
  - npm install
script:
  - py.test --pep8 --cov .
  - coveralls
